### ISSUE TITLE
Null Reivews

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#101]
when there are 0 reviews it should say "0 Reviews" NOT "Null reviews"
![img_0121 png](https://cloud.githubusercontent.com/assets/9375175/21384435/943d3e46-c790-11e6-9cfd-15e05f0ceb5e.jpg)

**Comment by shrikant-redorange** [comment]
Fixed from everywhere.

![img_1202](https://cloud.githubusercontent.com/assets/23091851/21392524/44ea97dc-c7b6-11e6-9167-b229065126ae.PNG)

**Comment by sachinrot** [comment]
NOT fixed

**Comment by sachinrot** [comment]
Never ever in the future mark things fixed when they are not fixed. Null issue comes to certain host when they dont have any review, you have shared screen shot of person who has 2 reviews

**Comment by sachinrot** [comment]
Got to Chat detail page, click on right side Blue icon, you will see Null reivew
